### ISSUE TITLE
Some questions about the applications of scRNAseq to metabolism.

### ISSUE THREAD

**Issue by xiaozhongshen** [wu-yc/scMetabolism#1]
Bro, I want to ask you some technical questions about this package.
From my perspective, this package is a combination of ALRA used for imputation of missing values and some tools related to gene signature analysis. I think it is neccessary to provide the database of some other important species, such as mouse and zebrafish. 
Another problem I am concerned about is the receptor-ligand communication between different cell types. If you can expand this  function in the package and elevate the efficiency of computation, I think this package will have a wider application in metabolism.

**Comment by wu-yc** [comment]
Hi, xiaozhong,

Current version of scMetabolism only supports human. We are still testing mouse scRNA-seq data.

**Comment by LiMo-bioxer** [comment]
> Hi, xiaozhong,
> 
> Current version of scMetabolism only supports human. We are still testing mouse scRNA-seq data.

Can we now analyze the mouse data. Thanks a lot

**Comment by hiraksarkar** [comment]
Same question
