### ISSUE TITLE
Error in sc.metabolism.Seurat

### ISSUE THREAD

**Issue by zj-sciencego** [wu-yc/scMetabolism#12]
Hello, when i did the first step to input my Seurat to quantify single-cell metabolism,it has problem as follow:
`> countexp.Seurat<-sc.metabolism.Seurat(obj =immune, method = "VISION", imputation = F, ncores = 1, metabolism.type = "KEGG")

Your choice is: KEGG
Start quantify the metabolism activity...
Loading data from C:/Program Files/R/R-4.0.2/library/scMetabolism/data/KEGG_metabolism_nc.gmt ...

Using 20447/30242 genes detected in 0.10% of cells for signature analysis.
See the `sig_gene_threshold` input to change this behavior.

Beginning Analysis

Computing a latent space for expression data...

Determining projection genes...
    Applying Threshold filter...removing genes detected in less than 2364 cells
      Genes Retained: 8259
    Applying Fano filter...removing genes with Fano < 2.0 MAD in each of 30 bins
      Genes Retained: 1781

Clustering cells...
Using latent space to cluster cells...
Error in igraph::cluster_louvain(g) : 
  REAL() can only be applied to a 'numeric', not a 'builtin'
In addition: Warning message:
In readSignaturesInput(signatures) : NAs introduced by coercion`

Firstly, i doubed that it was something wrong about my Seurat object. However, it had the same problem when i run the example "pbmc_demo.rda", how could i do to fix it? So many thanks!!

**Comment by wu-yc** [comment]
Please re install the vision v2.1.0. 
`devtools::install_github("YosefLab/VISION@v2.1.0")`

**Comment by lishuang0121** [comment]
Hello, when I did the first step to input my Seurat to quantify single-cell metabolism,it has problem as follow:
`> countexp.Seurat<-sc.metabolism.Seurat(obj =immune, method = "VISION")

Your choice is: KEGG
Start quantify the metabolism activity...
Loading data from /home/data/t100560/R/x86_64-pc-linux-gnu-library/4.3/scMetabolism/data/KEGG_metabolism_nc.gmt ...

Using 13656/13714 genes detected in 0.10% of cells for signature analysis.
See the `sig_gene_threshold` input to change this behavior.

Beginning Analysis

Computing a latent space for expression data...

Determining projection genes...
    Applying Threshold filter...removing genes detected in less than 132 cells
      Genes Retained: 3857
    Applying Fano filter...removing genes with Fano < 2.0 MAD in each of 30 bins
      Genes Retained: 676

Clustering cells...completed

Projecting data into 2 dimensions...
  Running method 1/1: tSNE30 ...

Evaluating signature scores on cells...

  |====================================================================================================| 100%, Elapsed 00:00
Evaluating signature-gene importance...

  |====================================================================================================| 100%, Elapsed 00:00
Creating 5 background signature groups with the following parameters:
  sigSize sigBalance
1       7          1
2      11          1
3      15          1
4      25          1
5      56          1
  signatures per group: 3000
Computing KNN Cell Graph in the Latent Space...

Evaluating local consistency of signatures in latent space...

  |====================================================================================================| 100%, Elapsed 00:00
  |====================================================================================================| 100%, Elapsed 00:17
  |====================================================================================================| 100%, Elapsed 00:00
Clustering signatures...

Computing differential signature tests...

  |====================================================================================================| 100%, Elapsed 00:00
  |                                                                                                           |   0%, ETA NA
Error in `[<-.data.frame`(`*tmp*`, , 2, value = 0) : 
  replacement has 1 row, data has 0
In addition: Warning message:
In readSignaturesInput(signatures) : NAs introduced by coercion

Firstly, i doubed that it was something wrong about my Seurat object. However, it had the same problem when i run the example "pbmc_demo.rda", how could i do to fix it? So many thanks!! 

I just tried after devtools::install_github("YosefLab/VISION@v2.1.0") and got the same error.
