### ISSUE TITLE
Would it be possible to access to the .cloupe files in the study?

### ISSUE THREAD

**Issue by jiazhen-rong** [wu-yc/scMetabolism#24]
Thank you for creating the tool and sharing the data of the study.
We are trying to use the .cloupe files (auto-generated from the 10X CellRanger pipeline) of the spatial datasets, however it is not available in the analyzed data or the raw data. Would it be possible to access to the .cloupe file of the eight ST datasets of P1~P4?
Or if not, may I know which samples in the raw data (https://www.biosino.org/node/project/detail/OEP001756) are corresponding to the ST-P1 ~P4?
Thank you for your time and help!

**Comment by wu-yc** [comment]
Hi Jiazhen, please check your mail. I have sent it to you.

Have a nice day

**Comment by jiazhen-rong** [comment]
Thank you very much for the help!
