### ISSUE TITLE
which cells to choose as input when studying difference between subtypes

### ISSUE THREAD

**Issue by chengwenxuan1997** [wu-yc/scMetabolism#3]
Hi, I am studying the metabolic differences between different subtypes of B cells. And when I take all cells (including B cells, panT, epithelia, and so on) and only B cells as input, I get some different conclusions. So I wonder which input I should choose as input when I study the metabolic characteristic of different cell subtypes. Thank you for your reply.

**Comment by wu-yc** [comment]
Hi Wenxuan,

In our testing data, we did not observe the inconsistency of metabolic scores between all cells and only cell subsets. Thanks for pointing out this interesting issue. Would you please provide the testing data and the parameters that you used?

Cheers, 
Yingcheng
