### ISSUE TITLE
DotPlot.metabolism(obj = countexp.Seurat, pathway = input.pathway, phenotype = "ident", norm = "y")", Error in [.data.frame(metadata, , input.parameter) : 选择了未定义的列

### ISSUE THREAD

**Issue by foelen** [wu-yc/scMetabolism#33]
Hi Wu yc !
I had a  problem as same as a problem you have closed, when i run this command "DotPlot.metabolism(obj = countexp.Seurat, pathway = input.pathway, phenotype = "ident", norm = "y")", Error in [.data.frame(metadata, , input.parameter) : 选择了未定义的列, I want to request you: how to fix this kind of error

**Comment by Leung300** [comment]
Maybe you need to check phenotype = 'ident', and substitute 'ident' with your cluster's name.
