### ISSUE TITLE
Adaptation for mouse data

### ISSUE THREAD

**Issue by jdarmitage** [wu-yc/scMetabolism#5]
Hi,

Thanks for this brilliant package. Is there any update on when the mouse version of this tool will be implemented? Or is there any way we can run this, at least partially on a mouse dataset (like converting the mouse metabolic genes to human orthologues)?

Best regards,
Jesse

**Comment by wu-yc** [comment]
Hi jdarmitage,

In the current version of scMetabolism, you can manually convert the gene names into human orthologues. scMetabolism 2.0 will support the mouse data or even more species. 

Cheers, 
Yingcheng
