### ISSUE TITLE
question about DotPlot.metabolism 

### ISSUE THREAD

**Issue by xutongran** [wu-yc/scMetabolism#6]
Hi Wu yc !
I had a similar problem, when i run this command "DotPlot.metabolism(obj = countexp.Seurat, pathway = input.pathway, phenotype = "ident", norm = "y")", Error in [.data.frame(metadata, , input.parameter) : 选择了未定义的列, I want to request you: how to fix this kind of error

**Comment by wu-yc** [comment]
You can just extract the metabolic activity matrix and visualize it by using ggplot. We will fix this in the next version of scMetabolism. 

Thanks again for your support.
